### ISSUE TITLE
PROFILE_NOT_FOUND

### ISSUE THREAD

**Issue by jacc** [gclem/overwatch-js#1]
```
owjs
    .getAll('xbl', 'us', 'Golden Wolf833')
    .then((data) => console.dir(data, {depth : 2, colors : true}) );
```

Returns the error "PROFILE_NOT_FOUND"

**Comment by jacc** [comment]
It seems that overwatch-js doesn't accept PSN or XBL queries. When will this be added?

**Comment by gclem** [comment]
@jaacks : Thx, i'll do this today.
