### ISSUE TITLE
Heroes object does not contain anything

### ISSUE THREAD

**Issue by deruga4** [gclem/overwatch-js#13]
When I try to get hero information, I get an empty object.

This is what I've attempted to do:

`console.log(data.quickplay.heroes);`

returns `{}`

Alternatively, when I do:

`console.log(data.quickplay.heroes.roadhog);`

returns `undefined`

**Comment by gclem** [comment]
Will check.

**Comment by gclem** [comment]
@deruga04 Can't reproduce, on which nickname ?

**Comment by deruga4** [comment]
MrBaka#11482

**Comment by gclem** [comment]
Can't reproduce.
