### ISSUE TITLE
Recent playoverwatch.com changes

### ISSUE THREAD

**Issue by Archomeda** [gclem/overwatch-js#14]
The website has been changed a bit recently:

- There are no more region based statistics; all region based URLs are redirected to the same profile now
- Searching accounts apparently now supports multiple results, and apparently you can use `https://playoverwatch.com/en-us/search/account-by-name/<name>` as a JSON endpoint directly

Maybe there are some more changes, but this is all I know of.

**Comment by gclem** [comment]
I'll look at it this week if I get some free time.

**Comment by gclem** [comment]
Just checked, and I don't see any troubles. All is working fine. 

Could you confirm please

**Comment by Archomeda** [comment]
I guess with the changes you made in 7a5c0a9 it fixed the issue of using tags with a dash instead of using the hashtag, since you explicitly replace it now. I didn't check how the search endpoint previously worked, so the rest might have stayed the same.

There's still the case of the removed regions. It currently works as is, but only because of the catch-all `https://playoverwatch.com/en-us/career/<platform>/<region>/<battletag>` that redirects to `https://playoverwatch.com/en-us/career/<platform>/<battletag>`. This might get removed later without notice. Regions are no longer used by the website. You might as well remove the region parameter them from the functions entirely, but this is a breaking change.

**Comment by gclem** [comment]
Will be plannned on next version. Thanks for the feedback @Archomeda
