### ISSUE TITLE
How to catch information...

### ISSUE THREAD

**Issue by tlegoc** [gclem/overwatch-js#15]
I want to create a Discord bot that show you your overwatch profile.
I know everythings I need to know, exept HOW TO CATCH INFORMATION FROM THE CONSOLE (Like player level or rank)
How to do it ?
Thanks !!
Edorion

**Comment by 0024t** [comment]
The actual code : `if (message.content.startsWith('OwStat'))
		{
			pseudo = message.content.split(' ', 2);
			owjs
			.getAll('pc', 'fr-fr', pseudo[1].split('#').join('-'))
			.then((data) => console.dir(data, {colors : true}));
			/*function embedow() {
				message.channel.send({embed: {
				color: 3447003,
				author: {
				  name: console.log(data.profile.nick),
				  icon_url: console.log(data.profile.avatar),
				},
				title: console.log(data.profile.nick) + '\'s profile',
				url: console.log(data.profile.url),
				fields: [{
					name: "Level :",
					value: console.log(data.profile.level)
				  },
				  {
					name: "Ranking :",
					value: console.log(data.profile.ranking)
				  },
				  {
					name: "Average eliminations :",
					value: console.log(data.profile.eliminations_average)
				  },
				  {
					name: "Average death :",
					value: console.log(data.profile.deaths_average)
				  }
				],
				timestamp: new Date(),
				footer: {
				  icon_url: client.user.avatarURL,
				  text: "© Example"
				}
			  	}
				});
			}
			setTimeout(embedow, 4000);
		}`
I dont know what is wrong, (I'm sure that's not the embed (embedow)), and the fonction `owjs
			.getAll('pc', 'fr-fr', pseudo[1].split('#').join('-'))
			.then((data) => console.dir(data, {colors : true}));`
send something. But in the console...

**Comment by AxeBane** [comment]
Might have something to do with the fact that you're literally typing `console.log(something)`

Remove the call to the console and just leave the actual values.

**Comment by tlegoc** [comment]
I'm new in node.js, so what do you mean with "Remove the call to the console and just leave the actual values." ? 
Personaly when i type console.log(something) it doesn't work (example : I type  console.log(data.profile.nick) and it say profile (or nick ) is undefined... )

**Comment by tlegoc** [comment]
And how i can convert it into string also ? Thanks !! 😀

**Comment by AxeBane** [comment]
`console.log(data.profile.nick)` -> `data.profile.nick`

**Comment by tlegoc** [comment]
Thanks ! I will try later !

**Comment by tlegoc** [comment]
It dont work... when I replace `console.log(data.profile.nick)` by `data.profile.nick`, the debugger say data is  undefined.
Same problem if I remove data (`profile.nick`), profile is undefined.

**Comment by gclem** [comment]
Push your code here please

**Comment by 0024t** [comment]
(My code is horrible, so be ready ^^)

`const Discord = require('discord.js');
let fs = require('fs');
var request = require('request');
var owjs = require('overwatch-js');
var owtableau;
var IsPlaying = false;
var difficulty = -1;
var AsLoadedTheDifficulty = false;
var NToFound = 0;
var Nbdecoups = 0;
var pseudo;
const bot = new Discord.Client()

bot.login('MzQ1MTQyNzQwMjA1Njk5MDcy.DNcvew.FbZbyhxcS9fckiUjwUi6RIjTI_k')

bot.on('ready', function () {
	console.log("Connected")
	bot.user.setGame('In dev !!')
})

bot.on('message', message => {
	function MsgResponse(Message, Response) {
		if (message.content === Message) {
			message.channel.sendMessage(Response)
		}
	}
	console.log(message.content);
	if (message.content.startsWith('Play Game')) {
		IsPlaying = true;
		message.channel.sendMessage('choose your difficulty : Noob, Good, Pro player, Instant death')
		difficulty = 0;
	}

	if (IsPlaying === true) {
		if (AsLoadedTheDifficulty === false) {
			if (message.content === "Noob") {
				message.channel.sendMessage('Noob difficulty loaded ! Found the number between 0 and 500 !')
				AsLoadedTheDifficulty = true;
				NToFound = Game1Init(1)
				difficulty = 1;
			}
			if (message.content === "Good") {
				message.channel.sendMessage('Good difficulty loaded ! Found the number between 0 and 750 !')
				AsLoadedTheDifficulty = true;
				NToFound = Game1Init(2)
				difficulty = 2;
			}
			if (message.content === "Pro player") {
				message.channel.sendMessage('Pro Player difficulty loaded ! Found the number between 0 and 1000 !')
				AsLoadedTheDifficulty = true;
				NToFound = Game1Init(3)
				difficulty = 3;
			}
			if (message.content === "Instant death") {
				message.channel.sendMessage('Instant death difficulty loaded ! Found the number between 0 and 100000 !')
				AsLoadedTheDifficulty = true;
				NToFound = Game1Init(4)
				difficulty = 4;
			}

		}

		if (AsLoadedTheDifficulty === true) {
			if (parseInt(message.content) > NToFound) {
				message.channel.sendMessage("Moins !!")
				Nbdecoups++;
			}
			else if (parseInt(message.content) < NToFound) {
				message.channel.sendMessage("Plus !!")
				Nbdecoups++;
			}
			else if (parseInt(message.content) == NToFound) {
				Nbdecoups++;
				message.channel.sendMessage("BRAVO " + message.author.tag + " !!! Tu as trouvé en " + Nbdecoups + " coups !!")
				NToFound = 0;
				AsLoadedTheDifficulty = false;
				difficulty = -1;
				IsPlaying = false;
				Nbdecoups = 0;
			}
		}

	}

	if (IsPlaying === false) {
		MsgResponse('ping', 'pong')
		MsgResponse('Bonjour', 'Bonjour ' + message.author.tag)
		MsgResponse('LOL', 'ROFL')
		MsgResponse('3.14159265358979323846264338', 'Arrête d\'écrire pi abruti')
	
		if (message.content.startsWith('OwStat'))
		{
			pseudo = message.content.split(' ', 2);
			var liste; //'https://owjs.ovh/all/pc/fr-fr/' + pseudo[1].split('#').join('-')
			var datad ;
			owjs
			.getAll('pc', 'eu', pseudo[1].split('#').join('-'))
			.then((data) => console.dir(data, {depth : 2, colors : true}));

			function embedow() {
				message.channel.send({embed: {
				color: 3447003,
				author: {
				  name: pseudo[1].split('#').join('-'),
				  icon_url: console.dir(data.profile.avatar),
				},
				title: pseudo[1] + '\'s profile',
				url: data.profile.url,
				fields: [{
					name: "Level :",
					value: profile.level
				  },
				  {
					name: "Ranking :",
					value: profile.ranking
				  },
				  {
					name: "Average eliminations :",
					value: profile.eliminations_average
				  },
				  {
					name: "Average death :",
					value: profile.deaths_average
				  }
				],
				timestamp: new Date(),
			  	}
				});
			}
			setTimeout(embedow(), 4000);
		}

	if (message.content.startsWith("Dé"))
	{
		var ValeurDe = getRandomInt(1,6)
		message.reply("Tu as lancé " + ValeurDe + " !!")
	}
	}
	if (message.content.startsWith("Retr0 shutdown")) {
		message.sendMessage('Déconnecté')
		bot.user.exit;
		process.exit(0)
	}
})

function Game1Init(difficulty) {
	if (difficulty === 1) {
		return getRandomInt(0, 500)
	}
	else if (difficulty === 2) {
		return getRandomInt(0, 750)
	}
	else if (difficulty === 3) {
		return getRandomInt(0, 1000)
	}
	else {
		return getRandomInt(0, 100000)
	}
}

function getRandomInt(min, max) {
	min = Math.ceil(min);
	max = Math.floor(max);
	return Math.floor(Math.random() * (max - min)) + min;
}`

**Comment by 0024t** [comment]
My code is horrible... Be ready !!

`const Discord = require('discord.js');
let fs = require('fs');
var request = require('request');
var owjs = require('overwatch-js');
var owtableau;
var IsPlaying = false;
var difficulty = -1;
var AsLoadedTheDifficulty = false;
var NToFound = 0;
var Nbdecoups = 0;
var pseudo;
const bot = new Discord.Client()

bot.login('MzQ1MTQyNzQwMjA1Njk5MDcy.DNcvew.FbZbyhxcS9fckiUjwUi6RIjTI_k')

bot.on('ready', function () {
	console.log("Connected")
	bot.user.setGame('In dev !!')
})

bot.on('message', message => {
	function MsgResponse(Message, Response) {
		if (message.content === Message) {
			message.channel.sendMessage(Response)
		}
	}
	console.log(message.content);
	if (message.content.startsWith('Play Game')) {
		IsPlaying = true;
		message.channel.sendMessage('choose your difficulty : Noob, Good, Pro player, Instant death')
		difficulty = 0;
	}

	if (IsPlaying === true) {
		if (AsLoadedTheDifficulty === false) {
			if (message.content === "Noob") {
				message.channel.sendMessage('Noob difficulty loaded ! Found the number between 0 and 500 !')
				AsLoadedTheDifficulty = true;
				NToFound = Game1Init(1)
				difficulty = 1;
			}
			if (message.content === "Good") {
				message.channel.sendMessage('Good difficulty loaded ! Found the number between 0 and 750 !')
				AsLoadedTheDifficulty = true;
				NToFound = Game1Init(2)
				difficulty = 2;
			}
			if (message.content === "Pro player") {
				message.channel.sendMessage('Pro Player difficulty loaded ! Found the number between 0 and 1000 !')
				AsLoadedTheDifficulty = true;
				NToFound = Game1Init(3)
				difficulty = 3;
			}
			if (message.content === "Instant death") {
				message.channel.sendMessage('Instant death difficulty loaded ! Found the number between 0 and 100000 !')
				AsLoadedTheDifficulty = true;
				NToFound = Game1Init(4)
				difficulty = 4;
			}

		}

		if (AsLoadedTheDifficulty === true) {
			if (parseInt(message.content) > NToFound) {
				message.channel.sendMessage("Moins !!")
				Nbdecoups++;
			}
			else if (parseInt(message.content) < NToFound) {
				message.channel.sendMessage("Plus !!")
				Nbdecoups++;
			}
			else if (parseInt(message.content) == NToFound) {
				Nbdecoups++;
				message.channel.sendMessage("BRAVO " + message.author.tag + " !!! Tu as trouvé en " + Nbdecoups + " coups !!")
				NToFound = 0;
				AsLoadedTheDifficulty = false;
				difficulty = -1;
				IsPlaying = false;
				Nbdecoups = 0;
			}
		}

	}

	if (IsPlaying === false) {
		MsgResponse('ping', 'pong')
		MsgResponse('Bonjour', 'Bonjour ' + message.author.tag)
		MsgResponse('LOL', 'ROFL')
		MsgResponse('3.14159265358979323846264338', 'Arrête d\'écrire pi abruti')
	
		if (message.content.startsWith('OwStat'))
		{
			pseudo = message.content.split(' ', 2);
			var liste; //'https://owjs.ovh/all/pc/fr-fr/' + pseudo[1].split('#').join('-')
			var datad ;
			owjs
			.getAll('pc', 'eu', pseudo[1].split('#').join('-'))
			.then((data) => console.dir(data, {depth : 2, colors : true}));

			function embedow() {
				message.channel.send({embed: {
				color: 3447003,
				author: {
				  name: pseudo[1].split('#').join('-'),
				  icon_url: console.dir(data.profile.avatar),
				},
				title: pseudo[1] + '\'s profile',
				url: data.profile.url,
				fields: [{
					name: "Level :",
					value: profile.level
				  },
				  {
					name: "Ranking :",
					value: profile.ranking
				  },
				  {
					name: "Average eliminations :",
					value: profile.eliminations_average
				  },
				  {
					name: "Average death :",
					value: profile.deaths_average
				  }
				],
				timestamp: new Date(),
			  	}
				});
			}
			setTimeout(embedow(), 4000);
		}

	if (message.content.startsWith("Dé"))
	{
		var ValeurDe = getRandomInt(1,6)
		message.reply("Tu as lancé " + ValeurDe + " !!")
	}
	}
	if (message.content.startsWith("Retr0 shutdown")) {
		message.sendMessage('Déconnecté')
		bot.user.exit;
		process.exit(0)
	}
})

function Game1Init(difficulty) {
	if (difficulty === 1) {
		return getRandomInt(0, 500)
	}
	else if (difficulty === 2) {
		return getRandomInt(0, 750)
	}
	else if (difficulty === 3) {
		return getRandomInt(0, 1000)
	}
	else {
		return getRandomInt(0, 100000)
	}
}

function getRandomInt(min, max) {
	min = Math.ceil(min);
	max = Math.floor(max);
	return Math.floor(Math.random() * (max - min)) + min;
}`

**Comment by 0024t** [comment]
My code is horrible, be ready... 
`const Discord = require("discord.js");
let fs = require("fs");
var request = require("request");
var owjs = require("overwatch-js");
var owtableau;
var IsPlaying = false;
var difficulty = -1;
var AsLoadedTheDifficulty = false;
var NToFound = 0;
var Nbdecoups = 0;
var pseudo;
const bot = new Discord.Client()

bot.login("MzQ1MTQyNzQwMjA1Njk5MDcy.DNcvew.FbZbyhxcS9fckiUjwUi6RIjTI_k")

bot.on("ready", function () {
	console.log("Connected")
	bot.user.setGame("In dev !!")
})

bot.on("message", message => {
	function MsgResponse(Message, Response) {
		if (message.content === Message) {
			message.channel.sendMessage(Response)
		}
	}
	console.log(message.content);
	if (message.content.startsWith("Play Game")) {
		IsPlaying = true;
		message.channel.sendMessage("choose your difficulty : Noob, Good, Pro player, Instant death")
		difficulty = 0;
	}

	if (IsPlaying === true) {
		if (AsLoadedTheDifficulty === false) {
			if (message.content === "Noob") {
				message.channel.sendMessage("Noob difficulty loaded ! Found the number between 0 and 500 !")
				AsLoadedTheDifficulty = true;
				NToFound = Game1Init(1)
				difficulty = 1;
			}
			if (message.content === "Good") {
				message.channel.sendMessage("Good difficulty loaded ! Found the number between 0 and 750 !")
				AsLoadedTheDifficulty = true;
				NToFound = Game1Init(2)
				difficulty = 2;
			}
			if (message.content === "Pro player") {
				message.channel.sendMessage("Pro Player difficulty loaded ! Found the number between 0 and 1000 !")
				AsLoadedTheDifficulty = true;
				NToFound = Game1Init(3)
				difficulty = 3;
			}
			if (message.content === "Instant death") {
				message.channel.sendMessage("Instant death difficulty loaded ! Found the number between 0 and 100000 !")
				AsLoadedTheDifficulty = true;
				NToFound = Game1Init(4)
				difficulty = 4;
			}

		}

		if (AsLoadedTheDifficulty === true) {
			if (parseInt(message.content) > NToFound) {
				message.channel.sendMessage("Moins !!")
				Nbdecoups++;
			}
			else if (parseInt(message.content) < NToFound) {
				message.channel.sendMessage("Plus !!")
				Nbdecoups++;
			}
			else if (parseInt(message.content) == NToFound) {
				Nbdecoups++;
				message.channel.sendMessage("BRAVO " + message.author.tag + " !!! Tu as trouvé en " + Nbdecoups + " coups !!")
				NToFound = 0;
				AsLoadedTheDifficulty = false;
				difficulty = -1;
				IsPlaying = false;
				Nbdecoups = 0;
			}
		}

	}

	if (IsPlaying === false) {
		MsgResponse("ping", "pong")
		MsgResponse("Bonjour", "Bonjour " + message.author.tag)
		MsgResponse("LOL", "ROFL")
		MsgResponse("3.14159265358979323846264338", "Arrête d\'écrire pi abruti")
	
		if (message.content.startsWith("OwStat"))
		{
			pseudo = message.content.split(" ", 2);
			var liste; //"https://owjs.ovh/all/pc/fr-fr/" + pseudo[1].split("#").join("-")
			var datad ;
			owjs
			.getAll("pc", "eu", pseudo[1].split("#").join("-"))
			.then((data) => console.dir(data, {depth : 2, colors : true}));

			function embedow() {
				message.channel.send({embed: {
				color: 3447003,
				author: {
				  name: pseudo[1].split("#").join("-"),
				  icon_url: console.dir(data.profile.avatar),
				},
				title: pseudo[1],
				url: data.profile.url,
				fields: [{
					name: "Level :",
					value: profile.level
				  },
				  {
					name: "Ranking :",
					value: profile.ranking
				  },
				  {
					name: "Average eliminations :",
					value: profile.eliminations_average
				  },
				  {
					name: "Average death :",
					value: profile.deaths_average
				  }
				],
				timestamp: new Date(),
			  	}
				});
			}
			setTimeout(embedow(), 4000);
		}

	if (message.content.startsWith("Dé"))
	{
		var ValeurDe = getRandomInt(1,6)
		message.reply("Tu as lancé " + ValeurDe + " !!")
	}
	}
	if (message.content.startsWith("Retr0 shutdown")) {
		message.sendMessage("Déconnecté")
		bot.user.exit;
		process.exit(0)
	}
})

function Game1Init(difficulty) {
	if (difficulty === 1) {
		return getRandomInt(0, 500)
	}
	else if (difficulty === 2) {
		return getRandomInt(0, 750)
	}
	else if (difficulty === 3) {
		return getRandomInt(0, 1000)
	}
	else {
		return getRandomInt(0, 100000)
	}
}

function getRandomInt(min, max) {
	min = Math.ceil(min);
	max = Math.floor(max);
	return Math.floor(Math.random() * (max - min)) + min;
}`

**Comment by tlegoc** [comment]
Wait 2 sec...

**Comment by tlegoc** [comment]
https://mega.nz/#!vkAXwYbA!3K-N_rTb9DTH4_O-pW38faQV6xCrxH5rkKXpBNJZO-s

notice that I hide the token, and the information appear in the console but can't be reached...

P.s.: I saw on your profile FR, are you frecnh ? It will be easyer to talk

**Comment by tlegoc** [comment]
Sorry, at the line 105 it's 
`				  icon_url: data.profile.avatar,`
and not 
`				  icon_url: console.dir(data.profile.avatar),`

**Comment by tlegoc** [comment]
Also the code is not optimized

**Comment by tlegoc** [comment]
I found the solution... thanks !!
