### ISSUE TITLE
Question: Search for player with GetAll

### ISSUE THREAD

**Issue by Riotline** [gclem/overwatch-js#19]
How do you search for a player with GetAll.

I'm trying to attach this to discord but I need it to search for the player while also getting all their stats.

**Comment by tlegoc** [comment]
I created a discord bot if you want. But i need to update it i will send you the code 😉

**Comment by tlegoc** [comment]
https://github.com/0024t/OverBot.js here it is.
Have fun ^^

**Comment by gclem** [comment]
@Riotline : GetAll asks for the exact tag.
If you would like to search a player, you can use : 

```
var owjs = require('overwatch-js');

//// Search for a player 
owjs
    .search('Zeya#2303')
```

You will get, all similar battletags, if you get one result, take the first and do a getAll in the promise. 
If more than one result, ask to choice a battletag, in the returned list.
