### ISSUE TITLE
returns a split() error when i try and use owjs.search()

### ISSUE THREAD

**Issue by KolCrooks** [gclem/overwatch-js#20]
The search function suddenly started returning an error when trying to use it. I narrowed it down to this part of the source code- overwatch.js:317. It is trying to split player.careerLink even though player.careerLink is undefined. player doesn't contain a careerLink object.

**Comment by gclem** [comment]
Will catch it today too.

Sorry for the latency

Please, provide the username used for this issue

**Comment by gclem** [comment]
Fixed. Thanks.
