### ISSUE TITLE
Get most played hero

### ISSUE THREAD

**Issue by tlegoc** [gclem/overwatch-js#21]
Is there any way to get the most played hero ?
Thanks

**Comment by gclem** [comment]
Yes of course. Will push it later today

**Comment by tlegoc** [comment]
@gclem Nice 👌

**Comment by gclem** [comment]
You will find it on "masteringHeroe", located in .competitive.global or .quickplay.global

**Comment by tlegoc** [comment]
Nice work !! I will add it to my bot soon.

**Comment by gclem** [comment]
https://owjs.ovh is also updated with overwatch-js 1.7..0
