### ISSUE TITLE
Competitive and Quickplay data almost empty

### ISSUE THREAD

**Issue by fecolinhares** [gclem/overwatch-js#22]
I'm using overwatch-js to check some users profile in batch, and recently all competitive and quickplay data is empty. Maybe some issue with playoverwatch.com parser ?

**Comment by Tresmos** [comment]
yeah same
![image](https://user-images.githubusercontent.com/32764592/41634345-f7de04c6-744b-11e8-95d4-af2c710e9086.png)

**Comment by tlegoc** [comment]
Same.

**Comment by gclem** [comment]
on it
Will be fixed today

**Comment by gclem** [comment]
Sorry for the delay,
Listening your feedbacks.

**Comment by tlegoc** [comment]
I Will try if it works later this day.

**Comment by gclem** [comment]
@fecolinhares Fine for you ?
