### ISSUE TITLE
Data empty again

### ISSUE THREAD

**Issue by J-Evolve** [gclem/overwatch-js#23]
I guess due to the switch to private profiles the data is empty again?

https://playoverwatch.com/en-us/news/patch-notes/pc#patch-47946

**Comment by Jiinjin** [comment]
Yep, to see your stats, you have to put your profile back to public in the game.

**Comment by J-Evolve** [comment]
And chance you can let users authorize to check their private profile still somehow?

**Comment by gclem** [comment]
Not sure.
Even in the game, data isn't available.
