### ISSUE TITLE
Structure change

### ISSUE THREAD

**Issue by cloverpi** [gclem/overwatch-js#27]
I've been writing a module of my own similar to this one and I've noticed that the structure has changed in a few subtle ways.  For example the old season 1 and 2 ranks are no longer in the page.  2) time played table field is now true time_played down to the second which is awesome.  

However it's also been reporting strange numbers for damage_done fields for some players, some of the time.  Right now for example, some players' heroes will display the same number for both hero_damage_done and hero_damage_done_most_in_game.

I suspect the overwatch web dev team are doing some work to move over to their new API that launched last week.  If I'm right, these changes will likely continue for some time and we may even see the frontend completely rewritten.

Hopefully Blizzard decides to share their shiny new overwatch API with the public, and we don't need to resort to this awful scraping junk.  :D

Thought you'd like to know ;)

**Comment by dfsoeten** [comment]
That would be amazing if they do, thanks for the info!
