### ISSUE TITLE
Hero-specific damage_done_average is returned as rounded thousands

### ISSUE THREAD

**Issue by Saalvage** [gclem/overwatch-js#6]
Example: https://playoverwatch.com/en-us/career/pc/eu/Salvage-11179
My average damage as Genji in QP is 6,362.44, however, returned for data.quickplay.heroes.genji.damage_done_average is 6.

This applies to both comp and QP.

Besides that small annoyance, I am really thankful for this awesome module!

**Comment by gclem** [comment]
Hi @Saalvage ,
Thanks, I really appreciate your feedback.

It's fixed, Enjoy. 

Gio.
