### ISSUE TITLE
Ranking !== Rank

### ISSUE THREAD

**Issue by AxeBane** [gclem/overwatch-js#7]
There's a mismatch between the SR that the API calls and the "rank" that it lists (i.e. Silver, Diamond, Master...)

Examples I can call upon are as follows:

My Account reads 3040 SR but displays the rank as Master, when it should be Diamond.
A friend's account reads 2772 SR, ranks Diamond. Should be Platinum.
A friend's alt ranks 2588 SR, ranks Diamond. Should be Platinum.
A random account I scraped off of BattleNet had an SR of 734, and classed as Gold. THIS IS BRONZE.

Clearly there's some kind of issue with how the API interprets the ranking. It's probably a simple fix.

**Comment by gclem** [comment]
Thanks AxeBane,
Will investigate to fix this.

I'm based on the ranking image, seems has been changed

**Comment by gclem** [comment]
Done 

Thx for the feedback
