### ISSUE TITLE
Node versions > 6

### ISSUE THREAD

**Issue by Archomeda** [gclem/overwatch-js#9]
Hey there!

I noticed that I cannot use overwatch-js with any Node version above 6. I suppose it's compatible with higher versions, but I haven't fully tested it. Can you take a look at 

```
"engines": {
  "node": "6.0.0"
},
```

inside package.json and support higher versions?

**Comment by gclem** [comment]
Think all versions can be used. I'll check that.

**Comment by Archomeda** [comment]
Thanks! 😄
